name: YEPPDash

services:
  backend:
    image: mcmodersd/yeppdash:backend-latest
    container_name: YEPPDash-Backend
    restart: unless-stopped
    pull_policy: always
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      Database__User: ${DATABASE_USER}
      Database__Password: ${DATABASE_PASSWORD}
      Twitch__ClientId: ${TWITCH_CLIENT_ID}
      Twitch__ClientSecret: ${TWITCH_CLIENT_SECRET}
    ports:
      - 8080:8080/tcp

  frontend:
    image: mcmodersd/yeppdash:frontend-latest
    container_name: YEPPDash-Frontend
    restart: unless-stopped
    pull_policy: always
    ports:
      - 4000:4000/tcp

networks:
  default:
    name: YEPPDash-Network