name: YEPPDash

services:
  backend:
    image: mcmodersd/yeppdash:backend-latest
    container_name: YEPPDash-Backend
    restart: unless-stopped
    pull_policy: always
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      DbTarget: ${DB_TARGET:-Dev}
      ConnectionStrings__HelixDev: ${CONNECTIONSTRINGS__HELIXDEV:-}
      ConnectionStrings__HelixProd: ${CONNECTIONSTRINGS__HELIXPROD:-}
      ConnectionStrings__YeppDashDev: ${CONNECTIONSTRINGS__YEPPDASHDEV:-}
      ConnectionStrings__YeppDashProd: ${CONNECTIONSTRINGS__YEPPDASHPROD:-}
      Twitch__ClientIdDev: ${TWITCH__CLIENTIDDEV:-}
      Twitch__ClientIdProd: ${TWITCH__CLIENTIDPROD:-}
      Twitch__ClientSecretDev: ${TWITCH__CLIENTSECRETDEV:-}
      Twitch__ClientSecretProd: ${TWITCH__CLIENTSECRETPROD:-}
      Twitch__RedirectUri: ${TWITCH__REDIRECTURI}
      Spotify__ClientIdDev: ${SPOTIFY__CLIENTIDDEV:-}
      Spotify__ClientIdProd: ${SPOTIFY__CLIENTIDPROD:-}
      Spotify__ClientSecretDev: ${SPOTIFY__CLIENTSECRETDEV:-}
      Spotify__ClientSecretProd: ${SPOTIFY__CLIENTSECRETPROD:-}
      Spotify__RedirectUriDev: ${SPOTIFY__REDIRECTURIDEV:-}
      Spotify__RedirectUriProd: ${SPOTIFY__REDIRECTURIPROD:-}
      AllowedFrontendOrigins__0: ${ALLOWEDFRONTENDORIGINS__0}
      AllowedFrontendOrigins__1: ${ALLOWEDFRONTENDORIGINS__1}
      AllowedFrontendOrigins__2: ${ALLOWEDFRONTENDORIGINS__2}
    ports:
      - 8080:8080/tcp

  frontend:
    image: mcmodersd/yeppdash:frontend-latest
    container_name: YEPPDash-Frontend
    restart: unless-stopped
    pull_policy: always
    ports:
      - 4000:4000/tcp

networks:
  default:
    name: YEPPDash-Network